### ISSUE TITLE
VideoSummary.csv

### ISSUE THREAD

**Issue by oToToT** [janice-cat/GenPhys2019FALL#1]
As title, the csv file on github only contains 0 and 1.

It might be a mistake while exporting data with floating number.

Also, I’m wondering whether the full score should be 1 or 6?

**Comment by janice-cat** [comment]
Sorry for not explaining this record. It shows whether you submitted a video link for each hw.
(The grade of hw will not show in this github repo, but will appear in **CEIBA>學習成績(grades)>vPhysics HW**. And you will only see your grade.)

- 1: You have submitted the video link.
- 0: You haven't submitted.

If you've followed our rule (upload to youtube and comment the url), but you don't see a record "1", then please inform me. 😅
